### ISSUE TITLE
CVNN for MNIST or CIFAR classification

### ISSUE THREAD

**Issue by singhsukhendra** [NEGU93/cvnn#1]
Hello Sir, can you tell, whether and how  we can use CVNN for MNIST or CIFAR classification???

**Comment by NEGU93** [comment]
Hello,

Well MNIST and CIFAR are real-valued data so it will make no sense to use a CVNN (Complex-Valued Neural Networks).

There is an example on MNIST however in the [documentation](https://complex-valued-neural-networks.readthedocs.io/en/latest/code_examples/mnist_example.html) but you will be using an RVNN (Real-Valued Neural Network).

You can do some transformation to complex like making a Fourier Transform in which case you will have complex data. If that is the case, the only difference with the example on the link is that in each layer you should change `input_dtype=np.float32` to `input_dtype=np.complex64`. My library distinguishes between CVNN and RVNN according to the `input_dtype` parameter.

What is your goal exactly? I could give you further advice if you detail your application a little bit more.

**Comment by singhsukhendra** [comment]
I want to compare performance of  RVNN and CVNN on a same dataset , same number of epochs even if it requires transformation from real to complex.Can I do that?

**Comment by NEGU93** [comment]
Sorry for the delay. 

You inspired me into doing more documentation with each use case [here](https://complex-valued-neural-networks.readthedocs.io/en/latest/getting_started.html). For your particular case, I would recommend [this](https://complex-valued-neural-networks.readthedocs.io/en/latest/montecarlo.html#other-helper-function) if you already have a complex dataset to use and [this function](https://complex-valued-neural-networks.readthedocs.io/en/latest/experiments/correlation_noise.html) if you do not have a dataset and want to compare with any complex dataset.

Both examples will create a CVNN MLP and an RVNN equivalent and run statistics compared them using many iterations of each. The only difference is that one function you must give the dataset as input whereas in the other you do not.

Of course, if you want a more low-level approach so you can further understand what is going on you should go directly to the [CvnnModel docs](https://complex-valued-neural-networks.readthedocs.io/en/latest/cvnn.html)

**Comment by NEGU93** [comment]
@singhsukhendra are your questions answered? Can I close the Issue?
