### ISSUE TITLE
`fan_in` is None after a layer with `zrelu` activation

### ISSUE THREAD

**Issue by jonasdaugalas** [NEGU93/cvnn#13]
Hi @NEGU93 ,

Thanks again for keeping this package updated.

I have noticed an issue with the `zrelu` activation. The problem is that a layer (in sequential model) that goes after `zrelu` activation fails to initialize with an error saying that `fan_in` is of NoneType. It seems fine with other activation functions.

See here a short notebook reproducing the issue: https://gist.github.com/jonasdaugalas/e8a3c44055321f706081b4c4374597d6

Do you have an idea what could be wrong here?

**Comment by NEGU93** [comment]
The issue should be solved from version 1.1.64.

Thank you for reporting the issue.
