### ISSUE TITLE
ComplexUpSampling2D is too slow compiling

### ISSUE THREAD

**Issue by betances** [NEGU93/cvnn#14]
Hello!

There are a problem with ComplexUpSampling2D: Is too slow (overmuch) compiling.

For now, to skip this problem I am doing something like this:

def CUpsampling2D(x):
   r = UpSampling2D((2, 2))(tf.math.real(x))
   i = UpSampling2D((2, 2))(tf.math.imag(x))
   return tf.dtypes.complex(r, i, name=None)

But if I have time, I could calmly review to see how it can be solved. 

Thank you for your code. It is being very useful for my master. :-)

**Comment by NEGU93** [comment]
Thank you for the feedback. I will try to give it a look.
Indeed, it's hard for me in many ways to keep up with TensorFlow performances. However, if it's too much I will try to take a look.

Does this happen with bilinear or nearest interpolation? or both?
If you can, could you provide an idea of time difference?

Regards,

**Comment by betances** [comment]
This code is taking 15 minutes to compile

in1 = Input(shape=(64,64,1),dtype=tf.complex64)
out = ComplexUpSampling2D()(in1)
model = Model(inputs=in1, outputs=out)

I proved disabling the eager execution, but it does not improve.

**Comment by NEGU93** [comment]
To compile! I miss-read and thought it was to run. Ok, there is definitively a problem. I will take a look. Thank you!

**Comment by betances** [comment]
No. Once compiled, it runs very well.

**Comment by NEGU93** [comment]
Great, I created the [gist](https://colab.research.google.com/gist/NEGU93/cbdbc6dad79af2150b84b1da75bc668d/untitled5.ipynb) and indeed it takes ages to compile.

One important remark, the code you sent me you use the `Input` layers, is that from TensorFlow? If so, be careful! The last time I checked, even if you use `complex64` it casts the input to `float32` and it tells you nothing. Probably it changed in newer versions but maybe it didn't.

**Comment by betances** [comment]
I proved te input in this [gist](https://colab.research.google.com/gist/betances/ed65e9707969bbf94c7a5e1494ddd732/untitled0.ipynb), and it seems to work fine

**Comment by NEGU93** [comment]
Since [Version 1.1.70](https://pypi.org/project/cvnn/1.1.70/) this bug is fixed. 
However, as it can be seen [here](https://complex-valued-neural-networks.readthedocs.io/en/latest/layers/complex_upsampling2d.html), the `align_corners` parameter is not longer supported.
