### ISSUE TITLE
Killed!!

### ISSUE THREAD

**Issue by teodorf-bit** [NEGU93/cvnn#19]
When I run your test example my python kernel is "killed" when i run it on Ubuntu 16.04. 

It works on Mac though... Do you know what the problem is?

**Comment by NEGU93** [comment]
It's weird because I develop on Ubuntu... It should work. What is the error message?

**Comment by teodorf-bit** [comment]
Sorry it was Ubuntu 18.04 ....

it just says "Killed"

**Comment by NEGU93** [comment]
I have a few questions.
1. How do you run the script.
2. You get no output at all?
3. Have you tried running a TensorFlow model and it works fine?
4. Can you give me the exact script/s and tell me how you run it so I test it myself?

Thank you.

**Comment by teodorf-bit** [comment]
My apologies... It seems its python malfunctioning. You can close and remove this as its not related yo your package itself....
