### ISSUE TITLE
examples/cv-cnn.py is broken

### ISSUE THREAD

**Issue by wisecat57** [NEGU93/cvnn#2]
It says
```
from cvnn.layers import Convolutional, MaxPooling, Flatten, Dense, AvgPooling
ImportError: cannot import name 'Convolutional' from 'cvnn.layers' (C:\Users\Envoy\anaconda3\lib\site-packages\cvnn\layers.py)
```
and when I checked the layers file I couldn't see any conv class

**Comment by NEGU93** [comment]
Yes indeed. I deleted that example.
I am working in a branch that is suffering a HUGE change in all the code structure. I will be merging it soon (the first week of January). It will support Complex Convolutional Layers and more. 
For the moment only Complex Dense is supported. Sorry for the inconvenience.

**Comment by NEGU93** [comment]
@wisecat57 Complex Convolution layers work now since 1.0.0 release version.
