### ISSUE TITLE
CVNN API 3D layers

### ISSUE THREAD

**Issue by AVON257** [NEGU93/cvnn#22]
Hi, 

Can I just say firstly that I love you library sir? As I have been testing it on a pneumonia detection system, and it works beautifully, but I have also had a problem with attempting to make it work on 3D images.

Now to the best of my knowledge that maybe a problem with Tensor flow nightly rather than with CVNN, but I thought you should know about that.

Tom T.

P.S. I too have a very strong interest in machine learning algorithms of this type, and I am actively trying to do some research in the same area, only with Bayesian networks mostly rather than deep learning ones.

**Comment by NEGU93** [comment]
Hello,

Thank you for your kind comments. 
I am glad that my tool is useful for your applications and please don't forget to cite me if you do any kind of publications.

The problem you are having with 3D models is an implementation issue or a results issue?

If there are results which are not good I must say it happened the same for me. 2D conv nets work great and better than real conv nets but on 3d I don't get very good results (not better than real-valued conv 3d networks.

It can be possible then that there is a bug on my code here. I will look for it further.

Cordially,

Agustín.

**Comment by AVON257** [comment]
Hi,

It's an implementation problem, I think it's in tensorflow rather than
cvnn, but you can rest assured that I am citing you in my work that uses
your library.

Maybe if I get to know it better, I could develop new layers for cvnn? Like
make more layers from tensorflow work with it? Or fix the 3D convolutional
one?

Tom T.

**Comment by AVON257** [comment]
Do I have your permission, to try and implement new layers in cvnn? Like
for example, a complex valued version, of the new tensorflow Conv2DLSTM one?

**Comment by NEGU93** [comment]
If you give me a mwe (you can even use [google - colab](https://colab.research.google.com/) and run it on cloud) and use this at the start `!pip install cvnn`.

Regarding your question about making a contribution. You can [fork](https://docs.github.com/en/get-started/quickstart/fork-a-repo) the project and then work on a branch. Once your code is done you can do a [pull request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) for me to review it and merge it to my project.

Regards,

**Comment by NEGU93** [comment]
Thank you for those kind words.

It is true that I won't have time for implementing a Conv2DLSTM but if you have any bugs on my implementations like Conv3D or anything don't hesitate to report it with an issue. 

I am for the moment closing this issue.

Regards,
