### ISSUE TITLE
Error: Inputs to a layer should be tensors. Got: <cvnn.layers.core.ComplexInput object at ...>

### ISSUE THREAD

**Issue by giuspillo** [NEGU93/cvnn#23]
Hi @NEGU93 
First of all thank you for this great library :)

I'm experiencing an error on a model; in particular, I have these two lines

input_users = complex_layers.ComplexInput(input_shape=(dim_embeddings))
x1 = complex_layers.ComplexDense(512, activation="cart_relu")(input_users)

The last line raises the following TypeError: Inputs to a layer should be tensors. Got: <cvnn.layers.core.ComplexInput object at 0x0000012D118F4FD0>

I understood that the input for this model must be ComplexInput (that's why I'm using it), but I have no idea about how to face this issue. Can you please help me? :)

**Comment by NEGU93** [comment]
Dear @giuspillo ,

Why did you close the issue? Did you find the solution? If so, could you post the answer for future developers who might have the same question?

Regards,
