### ISSUE TITLE
ValueError: Unknown loss function:ComplexAverageCrossEntropy

### ISSUE THREAD

**Issue by zeneggar** [NEGU93/cvnn#24]
【Succeed】from cvnn.losses import ComplexAverageCrossEntropy
【When using lossfunction:】loss='ComplexAverageCrossEntrop()'
【Error happens】ValueError: Unknown loss function:ComplexAverageCrossEntropy

When I use another loss function (Complex Mean Square Error), the same error happens.
Can you give me some advice to find the reason? 
If I post two times of this issure, please ignore one or delete.
Thank you very much. 
Frank

**Comment by zeneggar** [comment]
Sorry that I just find the reason.
loss='ComplexAverageCrossEntrop()'    should be changed to     loss=ComplexAverageCrossEntrop()
And the issue is solved.
Thanks.
Frank

**Comment by NEGU93** [comment]
Try removing the ' when initializing the class.

**Comment by zeneggar** [comment]
Thank you. It works.
