### ISSUE TITLE
ModuleNotFoundError: No module named 'cvnn.montecarlo'

### ISSUE THREAD

**Issue by AmberJouleDay** [NEGU93/cvnn#36]
I installed cvnn with `pip install cvnn[full]` however when I try to run the code from [https://complex-valued-neural-networks.readthedocs.io/en/latest/experiments/correlation_noise.html](here) I am getting the following error: **ModuleNotFoundError**: No module named '`cvnn.montecarlo`'

**Comment by NEGU93** [comment]
Hello,
Indeed, montecarlo module has been deleted from latest versions. I decided to shorten the library's scope and keep only the things more closely related to how tensorflow works for example. You can still access the module if you install older versions of the code. You can try looking for that in GitHub.

I believe the documentation link is also not longer available for the same reason.
