### ISSUE TITLE
Unknown activation function 'cart_relu': Please ensure this object is passed to 'custom objects' argument

### ISSUE THREAD

**Issue by Priyanshu-bee** [NEGU93/cvnn#37]
getting this error while trying to use complex activation functions with ComplexConv layers. Doesn't give any error while using the complex activations with the complex dense layer....

**Comment by NEGU93** [comment]
Could you please provide a Minimum Working Example (MWE) to reproduce the error? A plus would be the working scenario.

Thank you

**Comment by Priyanshu-bee** [comment]
from tensorflow.keras import datasets, models
import cvnn.layers as complex_layers 

model = models.Sequential()
model.add(complex_layers.ComplexConv2D(32, (3, 3), activation='cart_relu', input_shape=(32, 32, 3), dtype=np.float32))

running the above is causing the given error, it is working when replacing activation with just 'relu'. As far as I could understand while defining Complex conv layers you have imported activations from tensorflow.keras and then used activations.get(activation) which might be raising an issue as these activations are defined and created by you and importing t_activations might enable us to use these complex activations.

**Comment by NEGU93** [comment]
For me it's working. See it [here](https://colab.research.google.com/drive/1EzJZpw_hL2ATg9uWicBf6Gxq3RsukC6S).

**Comment by NEGU93** [comment]
Try updating cvnn version to the latest.

Also, beware that the example cast to np.float32 and not complex.

**Comment by Priyanshu-bee** [comment]
I used conda to install cvnn, that was giving the error. After doing pip install it works, thanks!!!
