### ISSUE TITLE
Best Activation Function in Complex Domain

### ISSUE THREAD

**Issue by Karn3003** [NEGU93/cvnn#39]
Hi, I am working with CVNN. As you already have worked with CVNN please let me know the best activation we can use in CVNN to obtain better performance like ReLU work out in ResNet etc

**Comment by NEGU93** [comment]
I always used [CReLU](https://complex-valued-neural-networks.readthedocs.io/en/latest/activations/relu.html#crelu).
But I did not do a big research about that. I suggest you do a bit of research papers and/or some experiments yourself. How about [this paper](https://arxiv.org/abs/1802.08026)?
