### ISSUE TITLE
 AttributeError: 'Tensor' object has no attribute 'numpy'

### ISSUE THREAD

**Issue by tahwaru** [NEGU93/cvnn#4]
Hi Barrachina,

I have been testing your CVNN library and the examples you provided.
For the convolutional code example in the readme file, I'm getting sometimes the following error 

........................\Anaconda3\lib\site-packages\cvnn\layers.py:965 pool_function  *
        res = [tf.convert_to_tensor(flat_in.numpy()[i][arg_ind]) for i, arg_ind in enumerate(flat_argmax.numpy())]
    AttributeError: 'Tensor' object has no attribute 'numpy'

Do you have a comment on it?
Sorry if this was already addressed somewhere and I missed it.

**Comment by NEGU93** [comment]
Hello.
Could you please confirm which version of cvnn are you using? 

Regards,

**Comment by tahwaru** [comment]
Hi,

version 1.0.0

Thanks,
Massa

**Comment by NEGU93** [comment]
Yes. I believe this is a known bug. Please update to las pip or conda version. I believe it would be fixed.

**Comment by tahwaru** [comment]
Sorry!!!
Thank you.
I'm updating.
