### ISSUE TITLE
Problem with loading complex valued model

### ISSUE THREAD

**Issue by pawziel8991** [NEGU93/cvnn#43]
I'd like to save a trained model and use it in different script in order to make actual predictions.
Unfortunately I cannot find it here:
https://complex-valued-neural-networks.readthedocs.io/en/stable/index.html
Is there a simple way to do it?

**Comment by NEGU93** [comment]
Being a tensorflow model, the model should be opened as any TF model. Otherwise, please copy here the MRE.

**Comment by pawziel8991** [comment]
I went around it with initiating the same model with copying the weights/parameters of trained one.
