### ISSUE TITLE
Data Parallel Distributed support

### ISSUE THREAD

**Issue by raj-brown** [NEGU93/cvnn#45]
Dear All-
Can I use `torch.nn.DataParallel` routine to train neural network for large complex value data.

Thanks!
Raj

**Comment by NEGU93** [comment]
I am quite unfamiliar with pytorch. 
This library uses tensorflow instead.
It is supposed to already work with GPU anyway, so should not be necessary.

**Comment by raj-brown** [comment]
@NEGU93 So I can use HOROVOD type of Framework for this. Right?

**Comment by NEGU93** [comment]
Again I ignore what HORVOD is. I won't be able to help you in this matter.
