### ISSUE TITLE
Type type error for "ComplexInput"

### ISSUE THREAD

**Issue by ashkanee** [NEGU93/cvnn#48]
When I use:

`model.add(complex_layers.ComplexInput(input_shape=(input_number,), dtype=np.complex64))
`
where "input_number=4", it says:

`ValueError: Invalid dtype: complex64`

Isn't it supposed to get complex inputs or I am missing something?
Thanks for the help.

**Comment by NEGU93** [comment]
Hello, sorry for the late reply.

Normally you don't need to specify it, the default is complex64. 
If you want to specify it, try using `tf.as_dtype(np.complex64)` instead.

**Comment by ashkanee** [comment]
Thanks for the reply :)
Actually the issue is similar to that of this one: [issue](https://github.com/NEGU93/cvnn/issues/50)
I close it so that we can follow there.
Thanks for the help
