### ISSUE TITLE
Error while adding a layer 

### ISSUE THREAD

**Issue by ashkanee** [NEGU93/cvnn#49]
When trying to add a layer using:

`        model.add(complex_layers.ComplexDense(15, activation='relu'))
`
I get:

`    self.w_r = self.add_weight('kernel_r',
TypeError: add_weight() got multiple values for argument 'shape'`

Can you please help?  Thanks

**Comment by NEGU93** [comment]
Hello, 

Sorry for the late reply.
I cannot realize what is wrong here. Can you give me the full code example? The [MRE](https://en.wikipedia.org/wiki/Minimal_reproducible_example#:~:text=In%20computing%2C%20a%20minimal%20reproducible,to%20be%20demonstrated%20and%20reproduced.)?

**Comment by ashkanee** [comment]
Hello,

 Thanks for the reply. This error is related to the issue here [https://github.com/NEGU93/cvnn/issues/50](url), so I think it is better to close this one.
